### PR TITLE
Add support for Gather.network

### PR DESCRIPTION
**Pull request by scream4ik**
Hello,

We recently launched our networks (mainnet, testnet and devnet).

You can verify the contract deployments here:
Explorer: https://explorer.gather.network/
RPC: https://mainnet.gather.network/

Live version: https://gnosis-safe.gather.network/

### CODE REVIEW

**Review by rmeissner — CHANGES_REQUESTED** [review]
The addresses of the contracts should be the same as the one of the other networks (there are 2 possible versions: with eip 155 and without). 

If there is a difference please outline why ;)

**Comment by rmeissner** [comment]
Closed due to inactivity. Reopen if requested changes have been applied.

**Comment by scream4ik** [comment]
@rmeissner related PRs are approved and merged by Gnosis team
https://github.com/gnosis/gnosis-py/pull/142
https://github.com/gnosis/safe-transaction-service/pull/513

The reason why we don't have the same addresses is that could not deploy with the deterministic address feature.
We could not do it because our chain has fixed gas cost

**Comment by rmeissner** [comment]
This repository will only support networks that use deterministic deployment. If you it is not possible to use the public deployment proxy (https://github.com/Arachnid/deterministic-deployment-proxy), then it should be possible with https://github.com/gnosis/safe-singleton-factory which is supported in the `1.3.0-libs.0` branch of the Safe contracts repo (similar to the flow for networks requiring replay protection: https://github.com/gnosis/safe-contracts/tree/v1.3.0-libs.0#replay-protection-eip-155)

**Comment by Uxio0** [comment]
> gnosis/safe-transaction-service#513

This was my mistake, I thought this PR was merged

**Pull request closed without merging**
