### PR TITLE
Adds contract addresses for Meter mainnet ( chain_id = 82 )

### PR DESCRIPTION
**Pull request by philipappiah**
Adds contract addresses for Meter mainnet ( chain_id = 82 )

### CODE REVIEW

**Comment by rmeissner** [comment]
Could you provide a browser url or rpc endpoint thatballows us to check for the deployed contracts?

**Comment by philipappiah** [comment]
The explorer for Meter mainnet is : https://scan.meter.io/
The rpc endpoint is : https://rpc.meter.io
You can check a contract on the explorer this way : https://scan.meter.io/address/<contract_address>

**Comment by rmeissner** [comment]
When checking the on-chain code it seems that this does not correspond 1:1 to the expected bytecode. Please make sure to checkout https://github.com/gnosis/safe-contracts/releases/tag/v1.3.0 before deploying (See https://github.com/gnosis/safe-contracts/tree/v1.3.0#deploy)

**Comment by rmeissner** [comment]
Close due to inactivity

**Pull request closed without merging**
