### PR TITLE
Add the deployment for Metadium Testnet & Metadium Mainnet

### PR DESCRIPTION
**Pull request by chikiru**
- Add address deploument for Metadium network
- Metadium Testnet
```
New RPC URL: https://api.metadium.com/dev
ChainID: 12
Symbol: META
Nickname: META Testnet
```

- Metadium Mainnet:
```
RPC URL: https://api.metadium.com/prod
ChainID: 11
Symbol: META
Nickname: META Mainnet
```

### CODE REVIEW

**Comment by fmrsabino** [comment]
Hey @chikiru ! Thanks for your contribution.

>  * Metadium Mainnet:
> 
> ```
> RPC URL: https://api.metadium.com/prod
> ChainID: 11
> Symbol: META
> Nickname: META Mainnet
> ```

The contracts don't seem to be deployed on this network though. (as they were on `META Testnet`)

**Review by rmeissner — CHANGES_REQUESTED** [review]
Contracts are not deployed at the specified addresses

**Comment by chikiru** [comment]
@rmeissner @fmrsabino Sorry I'm late. I deployed it on Metadium mainnet. Could you check it again.

**Review by rmeissner — APPROVED** [review]
Contract have been deployed to the expected addresses

**Pull request merged**
